### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tfiedlerdev** [tfiedlerdev/5sensor_dip#1]
- [ ] clone this repo to dhclab
- [ ] train dip model on only 5 sensors
- [ ] evaluate the model
- [ ] prepare unity environment
- [ ] create own recording with camera video and sensors attached as in original dip paper but without head sensor
![image](https://user-images.githubusercontent.com/29177177/163210793-16dabc64-c694-4f37-91ec-f543dc05e46b.png) 
- [ ] let our trained model predict pose configuration of own recording on dhclab
- [ ] visualize the predicted pose configuration in unity and compare with video
